sudo: required
dist: trusty
language: java
jdk:
 - oraclejdk8
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start              
deploy:
  provider: heroku
  api_key:
    secure: da05675c-e520-446d-8a18-97d28928a5c8
  app: bibfrog
